### ISSUE TITLE
isJsIrTransformationEnabled = true leads to compilaton exception.

### ISSUE THREAD

**Issue by vdshb** [Kotlin/kotlinx-atomicfu#358] opened 2023-10-29 16:58 UTC
I've tried to use `org.jetbrains.kotlin.plugin.atomicfu:org.jetbrains.kotlin.plugin.atomicfu.gradle.plugin:1.9.0` (1.9.10 have the same issue) plugin with

```
atomicfuCompilerPlugin {
    isJsIrTransformationEnabled = true
}
```

configuration and got a compile time exception:

```
java.lang.IllegalStateException: Exception while looking for the function `atomicfu_getValue` in package `kotlinx.atomicfu`: Collection contains no element matching the predicate.
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.TransformerUtilKt.referencePackageFunction(TransformerUtil.kt:275)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.getRuntimeFunctionSymbol(AtomicfuJsIrTransformer.kt:419)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.inlineAtomicFunction(AtomicfuJsIrTransformer.kt:335)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitCall(AtomicfuJsIrTransformer.kt:185)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitCall(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrReturn.transformChildren(IrReturn.kt:33)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitExpression(IrElementTransformer.kt:173)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitExpression(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitExpression(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitReturn(IrElementTransformer.kt:311)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitReturn(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitReturn(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.expressions.IrReturn.accept(IrReturn.kt:26)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.transformChildren(IrBlockBody.kt:32)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitBody(IrElementTransformer.kt:178)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitBody(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitBody(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitBlockBody(IrElementTransformer.kt:185)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitBlockBody(AtomicfuJsIrTransformer.kt:156)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitBlockBody(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:25)
	at org.jetbrains.kotlin.ir.expressions.IrBody.transform(IrBody.kt:22)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.transformChildren(IrFunction.kt:62)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitDeclaration(IrElementTransformer.kt:103)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitDeclaration(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitDeclaration(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitFunction(IrElementTransformer.kt:120)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitFunction(AtomicfuJsIrTransformer.kt:145)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitFunction(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitSimpleFunction(IrElementTransformer.kt:150)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitSimpleFunction(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitSimpleFunction(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:37)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrProperty.transformChildren(IrProperty.kt:59)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitDeclaration(IrElementTransformer.kt:103)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitDeclaration(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitDeclaration(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitProperty(IrElementTransformer.kt:144)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitProperty(AtomicfuJsIrTransformer.kt:141)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitProperty(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.declarations.IrProperty.accept(IrProperty.kt:49)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:24)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.declarations.IrClass.transformChildren(IrClass.kt:83)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitDeclaration(IrElementTransformer.kt:103)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitDeclaration(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitDeclaration(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitClass(IrElementTransformer.kt:110)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitClass(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer$AtomicTransformer.visitClass(AtomicfuJsIrTransformer.kt:109)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:73)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:24)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.declarations.IrFile.transformChildren(IrFile.kt:41)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.js.AtomicfuJsIrTransformer.transform(AtomicfuJsIrTransformer.kt:64)
	at org.jetbrains.kotlinx.atomicfu.compiler.extensions.AtomicfuClassLowering.lower(AtomicfuLoweringExtension.kt:46)
	at org.jetbrains.kotlinx.atomicfu.compiler.extensions.AtomicfuLoweringExtensionKt$runOnFileInOrder$1.visitFile(AtomicfuLoweringExtension.kt:61)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at org.jetbrains.kotlinx.atomicfu.compiler.extensions.AtomicfuLoweringExtensionKt$runOnFileInOrder$1.visitFile(AtomicfuLoweringExtension.kt:55)
	at org.jetbrains.kotlinx.atomicfu.compiler.extensions.AtomicfuLoweringExtensionKt$runOnFileInOrder$1.visitFile(AtomicfuLoweringExtension.kt:55)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:31)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at org.jetbrains.kotlinx.atomicfu.compiler.extensions.AtomicfuLoweringExtensionKt.runOnFileInOrder(AtomicfuLoweringExtension.kt:55)
	at org.jetbrains.kotlinx.atomicfu.compiler.extensions.AtomicfuLoweringExtension.generate(AtomicfuLoweringExtension.kt:35)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateModuleFragmentWithPlugins$lambda$11(klib.kt:435)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:107)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment$default(Psi2IrTranslator.kt:84)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateModuleFragmentWithPlugins(klib.kt:444)
	at org.jetbrains.kotlin.cli.js.klib.IrForKlibKt.generateIrForKlibSerialization(irForKlib.kt:100)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.processSourceModule(K2JsIrCompiler.kt:445)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:276)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:213)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:84)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:476)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:399)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:280)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:124)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:106)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:569)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1689)
	at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
Reproducer (see main-branch):
https://github.com/vdshb/atomic-plugin-reproducer-single-module/tree/main

JVM transformation seems to work correctly though:
```
atomicfuCompilerPlugin {
    isJvmIrTransformationEnabled = true
}
```

Disclaimer: I know that this plugin is probably never announced and might not be ready yet, but I decided that this bug-report might be helpful to someone anyway.

**Comment by mvicsokolova** [comment] 2023-11-13 17:36
Hi! 
The problem is that users are not supposed to apply the compiler plugin directly. `atomicfu-gradle-plugin` from the library is the main entry point for using kotlinx-atomicfu. `atomicfu-gradle-plugin` internally applies the compiler plugin and takes care of all the additional dependencies, including necessary runtime dependencies that were not resolved in your case and caused the attached error. 
So, for now, the only supported way to apply `atomicfu-gradle-plugin` is as described in the README, for your example project:

```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath("org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.22.0") // apply the gradle plugin here, do not apply the compiler plugin directly
    }
}

apply(plugin = "kotlinx-atomicfu")


plugins {
    kotlin("multiplatform") version "1.9.20"
}


kotlin {
    js(IR) {
        binaries.library()
        nodejs()
    }
    
    sourceSets {
        val commonTest by getting {
           ....
        }
    }

}
``` 

And to turn on JS IR transformation you should set the `kotlinx.atomicfu.enableJsIrTransformation=true` in your gradle.properties.

This way, everything compiles fine 🙂

**Closed by mvicsokolova** 2023-11-13 17:36 UTC
Labels: bug

**Comment by vdshb** [comment] 2023-11-21 21:39
Thanks for clarification!
