### ISSUE TITLE
KT 1.7.20 compatible

### ISSUE THREAD

**Issue by xtexChooser** [Kotlin/kotlinx-atomicfu#248] opened 2022-09-29 14:13 UTC
```
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.0.
     Required by:
         project : > org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.18.3 > org.jetbrains.kotlin:atomicfu:1.7.0
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 variant gradle70RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-runtime}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 variant gradle71RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.1, org.gradle.status=release, org.gradle.usage=java-runtime}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.


```

Maybe it can be solved by updating dependencies?

**Comment by diesieben07** [comment] 2022-10-01 14:25
The problem is Kotlin 1.7.20, not Gradle 7.5.1.

**Comment by xtexChooser** [comment] 2022-10-01 14:31
> The problem is Kotlin 1.7.20, not Gradle 7.5.1.

oh thanks for remind!

**Comment by Thomas-Vos** [comment] 2022-10-08 21:36
Same issue here with some more details: https://kotlinlang.slack.com/archives/C0KLZSCHF/p1662725020951299

I found a workaround which you can use with caution (it works for me):

Replace the following:
```
classpath("org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.18.3")
```
with
```
classpath("org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.18.3") {
    exclude("org.jetbrains.kotlin", "kotlin-gradle-plugin-api")
}
```
My project syncs, builds, and runs correctly now.

**Comment by headsvk** [comment] 2022-10-10 08:43
According to the [plugin details](https://mvnrepository.com/artifact/org.jetbrains.kotlinx/atomicfu-gradle-plugin/0.18.4), it has a runtime dependency on `org.jetbrains.kotlin:atomicfu:1.7.0` which can be updated to `1.7.20`. However, it looks like this update doesn't work with Gradle automatically.

I fixed this by adding `org.jetbrains.kotlin:atomicfu:1.7.20` as another classpath dependency.

**Comment by mvicsokolova** [comment] 2022-10-14 16:16
Sorry, for the late answer to this issue.
Yes, the problem was in the runtime dependency to `org.jetbrains.kotlin:atomicfu:1.7.0` that should have been updated to 1.7.20

It will be fixed in the next` kotlinx.atomicfu` release `0.18.5`, that will be published next week (with Kotlin updated to 1.7.20) .

**Comment by mvicsokolova** [comment] 2022-10-24 09:43
Hi! Yes, hopefully it will be released today.

**Comment by mvicsokolova** [comment] 2022-10-25 12:55
`0.18.5` is released

**Closed by mvicsokolova** 2022-10-25 12:55 UTC
Labels: bug
